config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # 会員側のルーティング設定
  scope module: :public do
    root to: 'homes#top'
    
    
    get '/homes/about' => 'homes#about'
    resources :items, only: [:index, :show]
    get '/customers/mypage' => 'customers#show'
    get '/customers/mypage/edit' => 'customers#edit'
    patch '/customers/mypage/update' => 'customers#update'
    get '/customers/withdrawal_confirm' => 'customers#withdrawal_confirm'
    patch '/customers/withdrawal' => 'customers#withdrawal'
    resources :cart_items, only: [:index, :create, :update]
    delete '/cart_items/:id' => 'cart_items#destroy'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :orders, only: [:new, :create, :index, :show]
    post '/orders/comfirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
  end
  # 管理者側のルーティング設定
  namespace :admin do
    root to: 'homes#top'
    resources :items
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end
  
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  def add_tax_price
    (self.price * 1.10).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  def index
  end
  
  def show
  end
  
  def edit
  end
  
  def update
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all.page(params[:page])
  end

  def new
    @items = Item.new
  end

  def create
    @items = Item.new(item_params)
    if @items.save
    redirect_to admin_items_path
    else
      @items = Item.new

      render new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @items = Item.find(params[:id])
  end

  def update
    @items = Item.find(params[:id])
    @items.update(item_params)
    redirect_to admin_item_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def show
  end
  
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
     super
   end

  # POST /resource/sign_in
   def create
     super
   end

  # DELETE /resource/sign_out
   def destroy
     super
   end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
   protected

  def configure_permitted_parameters
    added_attrs = [ :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if admin_signed_in? %>
    <div class="h-25 d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 border-bottom">
      <h5 class="my-0 mr-md-auto">LOGO</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <%= link_to admin_items_path, class: "p-2" do %><button type="button" class="p-2 btn btn-light">商品一覧</button><% end %>
        <%= link_to admin_customers_path, class: "p-2 ml-3" do %><button type="button" class="p-2 ml-3 btn btn-light">会員一覧</button><% end %>
        <%= link_to admin_root_path, class: "p-2 ml-3" do %><button type="button" class="p-2 ml-3 btn btn-light">注文履歴一覧</button><% end %>
        <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "p-2 ml-3 btn btn-light" %>
      </nav>
      </div>
    <% elsif customer_signed_in? %>
    <div class="h-25 d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 border-bottom">
      <h5 class="my-0 mr-md-auto">LOGO</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <%= link_to customers_mypage_path, class: "p-2" do %><button type="button" class="p-2 btn btn-light">マイページ</button><% end %>
        <%= link_to items_path, class: "p-2 ml-3" do %><button type="button" class="p-2 ml-3 btn btn-light">商品一覧</button><% end %>
        <%= link_to cart_items_path, class: "p-2 ml-3" do %><button type="button" class="p-2 ml-3 btn btn-light">カート</button><% end %>
        <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: "p-2 ml-3 btn btn-light" %>
      </nav>
      </div>
    <% else %>
    <div class="h-25 d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 border-bottom">
      <h5 class="my-0 mr-md-auto">LOGO</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <%= link_to homes_about_path, class: "p-2" do %><button type="button" class="p-2 btn btn-light">about</button><% end %>
        <%= link_to homes_about_path, class: "p-2 ml-3" do %><button type="button" class="p-2 ml-3 btn btn-light">商品一覧</button><% end %>
        <%= link_to new_customer_registration_path, class: "p-2 ml-3" do %><button type="button" class="p-2 ml-3 btn btn-light">新規作成</button><% end %>
        <%= link_to new_customer_session_path, class: "p-2 ml-3" do %><button type="button" class="p-2 ml-3 btn btn-light">ログイン</button><% end %>
      </nav>
      </div>
    <% end %>
    <%= yield %>
     <div id="footer" class="fixed-bottom p-4 px-md-4 mb-3 border-top"></div>
  </body>
</html>